spring:
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

app:
  security:
    jwt:
      refresh-cookie-secure: true

logging:
  structured:
    format:
      console: logstash
  level:
    root: INFO
    com.sanoli.fitradar: INFO
    org.springframework: WARN
